config/routes.rb
Rails.application.routes.draw do
  get 'source_files/display'

  get 'file/display'

  resources :projects 
  root 'projects#index'
  
  get '/showfile/:source_file_id' => 'projects#showfile', as: :show_file
  get 'update'   => 'projects#update_from_file'
  get 'clear'   => 'projects#clear_all_projects'
  
  resources :source_files,          only: [:create, :show]
  resources :comments,               only: [:create, :show]
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates :name, presence: true
  validates :content, presence:true
  
end

app/models/cuss.rb
class Cuss < ActiveRecord::Base
end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :source_files

end

app/models/source_file.rb
class SourceFile < ActiveRecord::Base
  belongs_to :project
  default_scope { order(:path => :asc) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper :all
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
  def create
    @comment = Comment.new(comment_params)
    if @comment.save
      comment_text = @comment.content
      Cuss.all.each do |filter|
        comment_text.sub!(filter.badword, filter.replacement)
      end
      @comment.content = comment_text
      @comment.save
      flash[:success] = "Comment created!"
      @comments = Comment.all
    respond_to do |format|
        format.html { redirect_to root_path }
        format.js
    end
    else
     # render 'projects/index'
    end
  end
  
  private

    def comment_params
      params.require(:comment).permit(:content, :name)
    end
  
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @projects = Project.all
    @comments = Comment.all
    @comment  = Comment.new
    

  end
  
  def show
    @project = Project.find(params[:id])
    @source_files = @project.source_files
  end

  def new
  end

  def create
  end
  
  def update_from_file
    
    Project.all.destroy_all
    #file = File.join(Rails.root, 'app', 'assets', 'svn_list1.xml')
    doc = Nokogiri::XML(File.open(File.join( Rails.root, 'app', 'assets', 'projects.xml' ) ) )
    entries =  doc.css('entry')
    
    entries.each do |entry|
      new_proj = Project.new
      new_proj.title = entry.css('name').text.to_s
      new_proj.date = entry.css(' date').text.to_s
      new_proj.version = entry.css('commit').attribute('revision').to_s
      new_proj.summary = "No Summary."
      new_proj.save
    end
    
    doc2 = Nokogiri::XML(File.open(File.join( Rails.root, 'app', 'assets', 'svn_list.xml' ) ) )
    entries2 =  doc2.css('entry')
    
    entries2.each do |entry|
      filetype = entry.attribute('kind')
      if (filetype.to_s == "file")
        filename = (entry.css('name').text).to_s
        filesize = (entry.css('size').text).to_s
        projectname = filename.match(/([^\/]*)\/.*/).captures[0].to_s
        file_mediatype = filename.match(/.*\.(.*)/).captures[0].to_s if filename.match(/.*\.(.*)/)
        file_mediatype = "other" unless filename.match(/.*\.(.*)/)
        case file_mediatype
          when "java", "hx", "rb"
            type_category = "Sourcecode"
          when "png", "jpg", "gif"
            type_category = "Image"
          when "txt"
            type_category = "Text"
          when "xml", "html"
            type_category = "Markup"
          else
            type_category = "Other"
        end
        proj = Project.find_by title: projectname
        proj.source_files.create!(path: filename, filesize:filesize, filetype:type_category)
      end
      
    end
    @projects = nil
    Cuss.all.destroy_all
    IO.foreach('badwords.txt') do |line|
      bad_word = line.to_s.match(/([^:]*):(.*)/).captures[0]
      good_word = line.to_s.match(/([^:]*):(.*)/).captures[1]
      Cuss.create(badword: bad_word, replacement: good_word)
    end
    
    respond_to do |format|
      format.html { redirect_to projects_path }
      format.js {render inline: "location.reload();" }
    end
  end
  
  def clear_all_projects
    Project.all.destroy_all
    Comment.all.destroy_all
    respond_to do |format|
      format.html { redirect_to projects_path }
      format.js {render inline: "location.reload();" }
    end
  end
  
  def showfile
    @source_file =  SourceFile.find(params[:source_file_id])  
    respond_to do |format|
      format.html #{ redirect_to projects_path }
      format.js  #{render  partial:'shared/display_svnfile' }
    end
  end

  private
  
end

app/controllers/source_files_controller.rb
class SourceFilesController < ApplicationController
  def show
    @source_file = SourceFile.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/source_files_helper.rb
module SourceFilesHelper
end

app/views/comments/_comment.html.erb
<div class="list-group-item">
  <span class="badge">Reply</span>
  <h4 class="list-group-item-heading"><%= comment.name %> &nbsp; <span class="label label-primary">ID: <%= comment.id %></span></h4> 
  <p class="list-group-item-text"><%= comment.content %></p>
</div>

app/views/comments/_comments.html.erb
<%= render @comments %>

app/views/comments/create.js.erb
$("#comments_grid").html("<%= escape_javascript(render('projects/comments_list')) %>");

app/views/layouts/_header.html.erb
<nav class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Rick Sheahan's Portfolio</a>
    </div>
    <div id="navbar" class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Update", update_path, remote: true %></li>
        <li><%= link_to "Clear", clear_path, remote: true %></li>
      </ul>
    </div><!-- /.nav-collapse -->
  </div><!-- /.container -->
</nav><!-- /.navbar -->

app/views/layouts/_project_box.html.erb
<div class="col-xs-6 col-lg-4">
  <h2><%= project.title %></h2>
    <ul>
        <li>Date: <%= project.date %></li>
        <li>Version: <%= project.version %></li>
        <li>Summary: <%= project.summary %></li>
    </ul>
  <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
</div><!--/.col-xs-6.col-lg-4-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>Rick Sheahan's Portfolio</title>
    <%= stylesheet_link_tag 'application', media: 'all',
                                           'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
</head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/projects/_comments_list.html.erb
<div id="comments_grid">
<%= render @comments %>
</div>

app/views/projects/_file_window.html.erb
<div id="filewindow">
<h1><%= @source_file.path %></h1>
<iframe src="https://subversion.ews.illinois.edu/svn/fa15-cs242/rssheah2/<%= @source_file.path %>"  width="100%" height="800">
    <p>File could not be loaded.</p>
</iframe>
</div>

app/views/projects/index.html.erb
<div class="container" id="base-index">

      <div class="row row-offcanvas row-offcanvas-right">

        <div class="col-xs-12 col-sm-9">
          <p class="pull-right visible-xs">
            <button type="button" class="btn btn-primary btn-xs" data-toggle="offcanvas">Toggle nav</button>
          </p>
          <div class="jumbotron">
            <h1>CS 242 Projects</h1>
            <p>Assignments from CS 242</p>
          </div>
          <div class="row">
            <% @projects.each do |project| %>
            <div class="col-xs-6 col-lg-4">
              <h2><%= project.title %></h2>
                <ul>
                    <li>Date: <%= project.date %></li>
                    <li>Version: <%= project.version %></li>
                    <li>Summary: <%= project.summary %></li>
                </ul>
              <%= link_to "View details", project, { :class=>"btn btn-default", :role=>"button" } %>
              <!--<p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>-->
            </div><!--/.col-xs-6.col-lg-4-->
            <% end %>
          </div><!--/row-->
        </div><!--/.col-xs-12.col-sm-9-->


      </div><!--/row-->
      <section class="micropost_form">
        <%= render 'shared/comment_form' %>
      </section>
      <div class="list-group" id="comments">
      <%= render 'comments_list' %>
      </div>

    
      <hr>

</div><!--/.container-->

app/views/projects/show.html.erb
<div class="jumbotron">
  <h2><%= @project.title %></h2>
    <ul>
        <li>Date: <%= @project.date %></li>
        <li>Version: <%= @project.version %></li>
        <li>Summary: <%= @project.summary %></li>
    </ul>
    
    <div id="filewindow"></div>


</div>
<ul class="list-group">
  <%= render @source_files %>
</ul>

app/views/projects/showfile.js.erb
$("#filewindow").html("<%= escape_javascript(render('projects/file_window')) %>");

app/views/shared/_comment_form.html.erb
<div class="comment-form">
<div class="well input-group input-group-lg"><%= form_for(@comment,  remote: true )do |f| %>
  <h3>Leave  a Comment <span class="label label-default">Be Nice!</span></h3>
  <%= render 'shared/error_messages', object: f.object %>
  
  <div class="field">
    <%= f.text_field :name, placeholder: "Name" %>
  </div>
  <div class="field">
    <%= f.text_area :content, placeholder: "Post a new comment", size: "100x10" %>
  </div>
  <%= f.submit "Post", class: "btn btn-primary" %>
<% end %>
</div>
</div>

app/views/shared/_display_svnfile.html.erb
<div id="filewindow">
<h1><%= @source_file.path %></h1>
<iframe src="https://subversion.ews.illinois.edu/svn/fa15-cs242/rssheah2/<%= @source_file.path %>"  width="100%" height="800">
    <p>File could not be loaded.</p>
</iframe>
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_hello.html.erb
<b>HELLO</b>

app/views/source_files/_source_file.html.erb
<li class="list-group-item">
  <span class="badge"><%= source_file.filesize %> bytes, <%= source_file.filetype %></span>
  <%= link_to source_file.path, source_file %>
  <%= link_to "Dispay", show_file_path(source_file.id), remote: true %>
</li>

app/views/source_files/show.html.erb
<div class="jumbotron">
<h1><%= @source_file.path %></h1>
<iframe src="https://subversion.ews.illinois.edu/svn/fa15-cs242/rssheah2/<%= @source_file.path %>"  width="100%" height="800">
    <p>File could not be loaded.</p>
</iframe>
</div>